### ISSUE TITLE
The conditional check 'auditd_manage_rules is boolean' failed

### ISSUE THREAD

**Issue by bschonec** [robertdebock/ansible-role-auditd#10]
## Describe the bug
When running the role unmodified and no additional variables supplied, the playbook errors with, "The conditional check 'auditd_manage_rules is boolean' failed. The error was: template error while templating string: no test named 'boolean'."

Error occurs at https://github.com/robertdebock/ansible-role-auditd/blob/master/tasks/assert.yml#L256

In the main.yml, you use https://github.com/robertdebock/ansible-role-auditd/blob/master/tasks/main.yml#L41 boolean filter.

I've looked through the ansible documentation but I haven't found documentation that supports "is boolean" check.

## Playbook

```yaml
---
- name: Import the playbook that installs all required packages
  import_playbook: auditd.yml
  tags:
    - auditd
    - 
    - ```

## Output

TASK [ansible-role-auditd : test if auditd_manage_rules is set correctly] **************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'auditd_manage_rules is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if auditd_manage_rules is boolean %} True {% else %} False {% endif %}"}

## Environment

- Control node OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
- Control node Ansible version: ansible 2.9.17
- Managed node OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)


Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
That's related to the version of Jinja you have installed. See `requirements.txt` what you need.
