### ISSUE TITLE
Multiple filters in rule.filters create malformed entries

### ISSUE THREAD

**Issue by mkbajzek** [robertdebock/ansible-role-auditd#3]
## Describe the bug
Within entries in `auditd_rules`, the `filters` field is parsed incorrectly on line 20 of `templates/custom.rules.j2`.

Given the following vars input:
`auditd_rules:`
`  - syscall: 'name'`
`    action: 'always'`
`    filter: 'exit'`
`    filters:`
`      - 'filter1'`
`      - 'filter2'`
`      - 'filter3'`
`    keyname: 'keyname'`

expected output is an entry of the form
`-a always,exit -S name -F filter1 -F filter2 -F filter3 -k keyname`

actual output is an entry of the form
`-a always,exit -S name -F filter1filter2filter3 -k keyname`

which can't be loaded by `auditd`.

A workaround for this is modifying the vars to include the "` -F `" that's missing from filters after the first one, but it leads to some confusing declarations (as below):
`auditd_rules:`
`  - syscall: 'name'`
`    action: 'always'`
`    filter: 'exit'`
`    filters:`
`      - 'filter1'`
`      - ' -F filter2'`
`      - ' -F filter3'`
`    keyname: 'keyname'`

## Environment

- Control node OS: macOS Catalina (10.15.4)
- Control node Ansible version: 2.9.9
- Managed node OS: CentOS 7

**Comment by robertdebock** [comment]
Well spotted, I made a modification:

```yaml
           filters:
             - auid!=4294967295
             - x=y
```

Results in:

```
 -a always,exit -F arch=b32 -S open -F auid!=4294967295 -F x=y -k my_keyname
```

Will push and release a new version.
