### ISSUE TITLE
Add support for architecture filters for syscalls

### ISSUE THREAD

**Issue by mkbajzek** [robertdebock/ansible-role-auditd#4]
## Proposed feature

A common use of filters within rules (see [open-scap](https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-standard.html#xccdf_org.ssgproject.content_rule_audit_rules_time_stime)) is specification of a particular architecture (as in `-a entry,always -F arch=b64 -S name -k key_name`), but this isn't supported by the current version of this role, since architecture must be specified before the `-S` argument.

## Rationale

In order to monitor one/more specific versions of a given syscall (and to adhere to best practices), `arch` should be specified when adding rules for `auditd`.

## Additional context

I propose supporting a field within the dictionaries in `auditd_rules` (`arch`) that adds a `-F` argument in the proper order when `syscall` lines are added to `/etc/audit/rules.d/custom.rules`.

**Comment by robertdebock** [comment]
Thanks @mkbajzek, I saw these issues just a few days ago, sorry for not spotting this earlier.

**Comment by robertdebock** [comment]
This is implemented in the last version.
