### ISSUE TITLE
Remove world writability on custom rules

### ISSUE THREAD

**Issue by isuftin** [robertdebock/ansible-role-auditd#8]
## Describe the bug
This isn't a bug so much as a security issue.

https://github.com/robertdebock/ansible-role-auditd/blob/master/tasks/main.yml#L35

This sets the permissions to `0666` on `custom.rules`. This allows for world writability. Ideally, this should be `0664` or more strict according to CIS recommendations 6.1.10 for CentOS 7 and CentOS 8

**Comment by isuftin** [comment]
https://github.com/robertdebock/ansible-role-auditd/pull/9

**Comment by robertdebock** [comment]
That's a good addition, thanks, I'll merge.

**Comment by robertdebock** [comment]
Thanks, new version released!

**Comment by isuftin** [comment]
Thank you
